apiVersion: apps/v1
kind: Deployment
metadata:
  name: nighteye-backend
spec:
  selector:
    matchLabels:
      component: nighteye-backend
  template:
    metadata:
      labels:
        component: nighteye-backend
    spec:
      containers:
        - name: nighteye-backend
          image: ghcr.io/rohankmr414/nighteye/backend:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: COIN_CAP_API_KEY
              value: ''
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: nighteye-backend-ip-service
spec:
  selector:
    component: nighteye-backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nighteye-frontend
spec:
  selector:
    matchLabels:
      component: nighteye-frontend
  template:
    metadata:
      labels:
        component: nighteye-frontend
    spec:
      containers:
        - name: nighteye-frontend
          image: ghcr.io/rohankmr414/nighteye/frontend:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: nighteye-backend-ip-service
            - name: API_PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: nighteye-frontend-ip-service
spec:
  selector:
    component: nighteye-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /?(.*)
            backend:
              service:
                name: nighteye-frontend-ip-service
                port:
                  number: 80
          - pathType: Prefix
            path: /?(.*)
            backend:
              service:
                name: nighteye-backend-ip-service
                port:
                  number: 8000