apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: nighteye-backend
  template:
    metadata:
      labels:
        app: nighteye-backend
    spec:
      containers:
        - name: nighteye-backend
          image: ghcr.io/rohankmr414/nighteye/backend:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: nighteye-backend-service
spec:
  selector:
    app: nighteye-backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nighteye-frontend
spec:
  selector:
    matchLabels:
      app: nighteye-frontend
  template:
    metadata:
      labels:
        app: nighteye-frontend
    spec:
      containers:
        - name: nighteye-frontend
          image: ghcr.io/rohankmr414/nighteye/frontend:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: nighteye-backend-service
            - name: API_PORT
              value: "8000"
